version: '3.9'
services:
  postgres:
    container_name: $APP_NAME
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $PG_DB_NAME
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
volumes:
  postgres-data: